// <auto-generated />
using MasterDetails.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterDetails.Migrations
{
    [DbContext(typeof(DatabaseCN))]
    partial class DatabaseCNModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MasterDetails.Models.PurchaseDetails", b =>
                {
                    b.Property<int>("PurchaseDtlsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseDtlsId"), 1L, 1);

                    b.Property<string>("Driscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrcuaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseDtlsId");

                    b.HasIndex("PrcuaseId");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("MasterDetails.Models.PurchaseInfo", b =>
                {
                    b.Property<int>("PrcuaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrcuaseId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PONO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProdctId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrcuaseId");

                    b.ToTable("PurchaseInfos");
                });

            modelBuilder.Entity("MasterDetails.Models.PurchaseDetails", b =>
                {
                    b.HasOne("MasterDetails.Models.PurchaseInfo", "PurchaseInfo")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PrcuaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInfo");
                });

            modelBuilder.Entity("MasterDetails.Models.PurchaseInfo", b =>
                {
                    b.Navigation("PurchaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
